### ISSUE TITLE
The build script generates a combined rom, but does not randomize items

### ISSUE THREAD

**Issue by ghost** [tewtal/alttp_sm_combo_randomizer_rom#1]
As said above. Ran the build script and it generated zsm.sfc in the build directory. This loaded in higan and ran well (which is awesome), but all items were in vanilla positions. I could transition between games just fine.

alttp_orig.sfc MD5: 03a63945398191337e896e5771f77173
sm_orig.sfc MD5: 21f3e98df4780ee1c667b84e57d88675
build/zsm.sfc MD5: ff2d32cb7341cbafd6c47572082ff3f6 (this is always the md5sum)

Python 3.6.4

**Comment by LagoLunatic** [comment]
The code for randomizing items is separate: https://github.com/tewtal/alttp_sm_combo_randomizer

**Comment by ghost** [comment]
I have now tried to use the randomizer via

`php artisan alttp:randomize .\zsm.sfc .\output\
`

It generates a file titled "sm_alttp - total_VT_no-glitches-v7.1_normal_standard_randomized_none_738270923.sfc" with an md5sum of "8874537f380c14fb6faaacdb79e7651f."

This is still not randomized, only seems to run in bsnes-plus (which is fine), and has serious bugs (the "intro fanfare" plays every few seconds in SM and there is no 'shooting' sfx).

I figure I must be doing something wrong.

**Comment by LagoLunatic** [comment]
Try this command:
`php artisan alttp:randomize --skip-md5 --variation=combo .\zsm.sfc .\output\`

**Comment by nitrostemp** [comment]
when using this tool you need to use "--mode open --variation combo" when using the build.bat to randomize the rom

**Comment by ghost** [comment]
Thanks - that worked perfectly! :D

**Comment by SmolBig** [comment]
Please close?
